name: Update Kubernetes Manifests

on:
  repository_dispatch:
    types: [image-updated-backend, image-updated-web]
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image name'
        required: true
        default: 'ghcr.io/hyjk826/testweb-dev'
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image variables
      id: vars
      run: |
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          echo "image=${{ github.event.client_payload.image }}" >> $GITHUB_OUTPUT
          echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT
          echo "commit_sha=${{ github.event.client_payload.commit_sha }}" >> $GITHUB_OUTPUT
          # 이벤트 타입에서 image_type 자동 추출
          # client_payload에 image_type이 있으면 우선 사용, 없으면 이벤트 타입에서 추출
          if [ -n "${{ github.event.client_payload.image_type }}" ]; then
            echo "image_type=${{ github.event.client_payload.image_type }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.action }}" == *"backend"* ]]; then
            echo "image_type=backend" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.action }}" == *"web"* ]]; then
            echo "image_type=web" >> $GITHUB_OUTPUT
          else
            echo "image_type=web" >> $GITHUB_OUTPUT
          fi
        else
          echo "image=${{ github.event.inputs.image }}" >> $GITHUB_OUTPUT
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          echo "commit_sha=manual" >> $GITHUB_OUTPUT
          echo "image_type=web" >> $GITHUB_OUTPUT
        fi

    - name: Update deployment image
      run: |
        if [ "${{ steps.vars.outputs.image_type }}" = "backend" ]; then
          echo "Updating backend API image..."
ㅊㅇ           sed -i "s|image: ghcr.io/hyjk826/testweb-dev-backend:.*|image: ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}|g" k8s/backend/backend-api.yaml
        else
          echo "Updating web server image..."
          sed -i "s|image: ghcr.io/hyjk826/testweb-dev:.*|image: ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}|g" k8s/frontend/deployment.yaml
        fi

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update ${{ steps.vars.outputs.image_type }} image to ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}"
        title: "Update ${{ steps.vars.outputs.image_type }} image to ${{ steps.vars.outputs.tag }}"
        body: |
          This PR updates the ${{ steps.vars.outputs.image_type }} image to `${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}`
          
          **Changes:**
          - Updated ${{ steps.vars.outputs.image_type }} deployment with new image tag
          - Image type: ${{ steps.vars.outputs.image_type }}
          
          **Triggered by:** ${{ github.event_name }}
          **Commit SHA:** ${{ steps.vars.outputs.commit_sha }}
        branch: update-${{ steps.vars.outputs.image_type }}-image-${{ steps.vars.outputs.tag }}
        delete-branch: true

    - name: Auto-merge PR
      if: steps.changes.outputs.changed == 'true' && github.event_name == 'repository_dispatch'
      run: |
        # PR이 생성된 후 자동으로 머지하는 로직
        # 실제 환경에서는 수동 검토 후 머지하는 것을 권장
        echo "PR created for image update"
